import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import img from "../public/sleepy.jpg"; // Adjust the path as necessary

import Menu from "./components/Nav/page";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} bg-gray-300 text-black/90 ${geistMono.variable} antialiased`}
      >
        <header className="bg-[#474a47] flex justify-between border-double border-t-12 border-b-12 ring-1 ring-white border-[#232323]/90 b p-3 shadow-2xl ">
          <Link href="/" className="flex max-md:px-2 max-md:scale-75 items-center gap-3 bg-[#D2D0D0FF] w-fit rounded-2xl mx-4 px-2">
            <Image className="rounded-[50%]" src={img} width={30} height={30} alt="Sleepy Panda Logo" />
            <div>
              <h1 className="font-bold max-md:scale-75  leading-tight">sleepy</h1>
              <h1 className="font-bold max-md:scale-75 leading-tight  font-sans  text-green-800">panda</h1>
            </div>
          </Link>

         <Menu />
        </header>
        {children}
        <div className="bg-[#474a47] text-white/60 border-dashed h-18 border-t-12 flex justify-center border-[#232323]/80 b p-3 shadow-2xl shadow-amber-50">
          <div className="rounded-2xl border p-1 border-[#454545] bg-[#373937]/80">© 2025{new Date().getFullYear() == 2025? "":new Date().getFullYear() } Sleepy Panda All rights Reserved</div>
        </div>
      </body>
    </html>
  );
}
